### ISSUE TITLE
The trouble with Triples

### ISSUE THREAD

**Issue by kkdavis14** [project-lux/data-pipeline#146]
from recent conversations with Peter, some problems with Collection Sets triples (but weirdly not archival set triples)

conceptClassifiedAs should not be on Collection Sets.

setClassifiedAs is missing from Collection Sets.

**Comment by kkdavis14** [comment]
re: the first issue, and why archival sets are getting workClassifiedAs:
archives Sets are pfx = "work" line 180ish in ML mapper
collection Sets are pfx = "concept" line 189 ish. 
the latter with note "Set here is Collection / Holdings. UI decision to put in with concepts".

**Comment by kkdavis14** [comment]
they're both then being created as triples line 366ish

**Comment by kkdavis14** [comment]
this is blocked by further understanding of why/what this UI decision was.

**Comment by kkdavis14** [comment]
unblocked if we go with the prelim fix in the PR, which is all that is required at the moment

**Comment by azaroth42** [comment]
Yeah, archives fall under works as they're not the physical things, but the intellectual hierarchy created by the archivists.
Dept sets fall under concepts because there's nowhere better for them to live :(

This will become unsupportable when we have user-generated collections... but until then it's the least bad option.
